// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo_service.proto

package echoTest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

import (
	"context"
	frog "github.com/yplusplus/frog"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var E_MethodId = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         1000,
	Name:          "echoTest.method_id",
	Tag:           "varint,1000,opt,name=method_id,json=methodId",
	Filename:      "echo_service.proto",
}

var E_MethodName = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         1001,
	Name:          "echoTest.method_name",
	Tag:           "bytes,1001,opt,name=method_name,json=methodName",
	Filename:      "echo_service.proto",
}

func init() {
	proto.RegisterExtension(E_MethodId)
	proto.RegisterExtension(E_MethodName)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

// Stub for EchoService service

type echoServiceStub struct {
	channel frog.RpcChannel
}

func NewEchoServiceStub(channel frog.RpcChannel) *echoServiceStub {
	return &echoServiceStub{channel}
}

func (stub *echoServiceStub) Echo(ctx context.Context, in *ProtoEchoRequest, out *ProtoEchoResponse) error {
	err := stub.Call(EchoService_ServiceDesc.Method(0), ctx, in, out)
	return err
}

func (stub *echoServiceStub) AsyncEcho(ctx context.Context, in *ProtoEchoRequest, out *ProtoEchoResponse) frog.RpcCall {
	return stub.Go(EchoService_ServiceDesc.Method(0), ctx, in, out)
}

func (stub *echoServiceStub) Echo2(ctx context.Context, in *ProtoEchoRequest, out *ProtoEchoResponse) error {
	err := stub.Call(EchoService_ServiceDesc.Method(1), ctx, in, out)
	return err
}

func (stub *echoServiceStub) AsyncEcho2(ctx context.Context, in *ProtoEchoRequest, out *ProtoEchoResponse) frog.RpcCall {
	return stub.Go(EchoService_ServiceDesc.Method(1), ctx, in, out)
}

func (stub *echoServiceStub) Call(method *frog.MethodDesc, ctx context.Context, in proto.Message, out proto.Message) error {
	call := stub.channel.Go(method, ctx, in, out)
	<-call.Done()
	return call.Error()
}

func (stub *echoServiceStub) Go(method *frog.MethodDesc, ctx context.Context, in proto.Message, out proto.Message) frog.RpcCall {
	return stub.channel.Go(method, ctx, in, out)
}

type EchoService interface {
	Echo(context.Context, *ProtoEchoRequest, *ProtoEchoResponse) error
	Echo2(context.Context, *ProtoEchoRequest, *ProtoEchoResponse) error
}

func RegisterEchoService(service EchoService, register frog.MethodsRegister) error {
	return frog.RegisterService(EchoService_ServiceDesc, service, register)
}

var (
	EchoService_ServiceDesc *frog.ServiceDesc
)

func init() {
	frog.GenerateServiceDesc(fileDescriptor1)
	EchoService_ServiceDesc = frog.ServiceDescriptor("EchoService_ServiceDesc")
}

func init() { proto.RegisterFile("echo_service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x4d, 0xce, 0xc8,
	0x8f, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x89, 0x85, 0xa4, 0x16, 0x97, 0x48, 0x29, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83,
	0xc5, 0x93, 0x4a, 0xd3, 0xf4, 0x53, 0x52, 0x8b, 0x93, 0x8b, 0x32, 0x0b, 0x4a, 0xf2, 0x8b, 0x20,
	0x6a, 0xa5, 0xb8, 0x40, 0x6a, 0x21, 0x6c, 0xa3, 0x95, 0x8c, 0x5c, 0xdc, 0xae, 0xc9, 0x19, 0xf9,
	0xc1, 0x10, 0xd3, 0x84, 0xbc, 0xb9, 0x58, 0x40, 0x5c, 0x21, 0x29, 0x3d, 0x98, 0x81, 0x7a, 0x01,
	0x20, 0x85, 0x20, 0xc1, 0xa0, 0xd4, 0xc2, 0x52, 0x90, 0x0d, 0xd2, 0x58, 0xe5, 0x8a, 0x0b, 0xf2,
	0xf3, 0x8a, 0x53, 0x95, 0xb8, 0x0e, 0xd8, 0x31, 0x9e, 0xb2, 0x63, 0x01, 0xa9, 0x10, 0xf2, 0xe5,
	0x62, 0x05, 0xc9, 0x19, 0x91, 0x6f, 0x1a, 0xf7, 0x01, 0x3b, 0xa6, 0x53, 0x76, 0xac, 0x20, 0x15,
	0x46, 0x56, 0x36, 0x5c, 0x9c, 0xb9, 0xa9, 0x25, 0x19, 0xf9, 0x29, 0xf1, 0x99, 0x29, 0x42, 0x72,
	0x7a, 0x10, 0x7f, 0xea, 0xc1, 0xfc, 0xa9, 0xe7, 0x0b, 0x96, 0xf3, 0x2f, 0x28, 0xc9, 0xcc, 0xcf,
	0x2b, 0x96, 0x78, 0xc1, 0xae, 0xc0, 0xa8, 0xc1, 0x1a, 0xc4, 0x01, 0xd1, 0xe1, 0x99, 0x62, 0xe5,
	0xc0, 0xc5, 0x0d, 0xd5, 0x9d, 0x97, 0x98, 0x9b, 0x4a, 0x50, 0xff, 0x4b, 0x90, 0x7e, 0xce, 0x20,
	0x2e, 0x88, 0x1e, 0xbf, 0xc4, 0xdc, 0x54, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0xe0, 0x8c,
	0xbc, 0x78, 0x01, 0x00, 0x00,
}
